version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
    depends_on:
      - Addition
      - Division
      - Multiplication
      - Subtraction
      - Equal
      - Exponent
      - Modulus
  # Add more services below
  addition:
    build: ./landing/app/Addition
    ports: 
      - 5051:5051
    networks:
      sample:
        aliases: 
          - addition
  
  multiplication:
    build: ./landing/app/Multiplication
    ports: 
      - 5052:5052
    networks:
      sample:
        aliases: 
          - multiplication
  
  subtraction:
    build: ./landing/app/Subtraction
    ports: 
      - 5053:5053
    networks:
      sample:
        aliases: 
            - subtraction

  division:
    build: ./landing/app/Division
    ports: 
      - 5054:5054
    networks:
      sample:
        aliases: 
          - division
  
  equal:
    build: ./landing/app/Equal
    ports:
      - 5055:5055
    networks:
      sample:
        aliases:
          - equalto
  
  exponent:
    build: ./landing/app/Exponent
    ports:
      - 5056:5056
    networks:
      sample:
        aliases:
          - exponent
  modulus:
    build: ./landing/app/Modulus
    ports: 
      - 5057:5057
    networks:
       sample:
          aliases:
            - modulus

networks:
  sample: